In [14]:
from model import ComposableModel
from util import read_config

model_cfg = read_config('notebook/linear.yaml')
model = ComposableModel("linear", model_cfg.modules)
model

ComposableModel(
  (linear): Mlp(
    (mlp): Sequential(
      (0): Linear(in_features=1, out_features=1, bias=True)
    )
  )
)

In [15]:
import torch
import numpy as np
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.MSELoss()

x = torch.from_numpy(np.random.rand(100, 1).astype(np.float32))
y = 2 * x + 1 + 0.1 * torch.randn(100, 1)

print(x)
print(y)

tensor([[0.9733],
        [0.9685],
        [0.1605],
        [0.4111],
        [0.0207],
        [0.2344],
        [0.2591],
        [0.7195],
        [0.3141],
        [0.0871],
        [0.3372],
        [0.8402],
        [0.6264],
        [0.7503],
        [0.5292],
        [0.7963],
        [0.1015],
        [0.4873],
        [0.1663],
        [0.3113],
        [0.4994],
        [0.1190],
        [0.3391],
        [0.5953],
        [0.8303],
        [0.0444],
        [0.1847],
        [0.9211],
        [0.1615],
        [0.1352],
        [0.1553],
        [0.1558],
        [0.1173],
        [0.0704],
        [0.8128],
        [0.6976],
        [0.0321],
        [0.2963],
        [0.9549],
        [0.6143],
        [0.8409],
        [0.5664],
        [0.4373],
        [0.5050],
        [0.3816],
        [0.7072],
        [0.0177],
        [0.4176],
        [0.8027],
        [0.4672],
        [0.8724],
        [0.0879],
        [0.3590],
        [0.9375],
        [0.4465],
        [0

In [16]:
model(x)

{'x': tensor([[1.2118],
         [1.2098],
         [0.8666],
         [0.9730],
         [0.8072],
         [0.8980],
         [0.9085],
         [1.1040],
         [0.9318],
         [0.8354],
         [0.9417],
         [1.1553],
         [1.0645],
         [1.1171],
         [1.0232],
         [1.1366],
         [0.8415],
         [1.0054],
         [0.8691],
         [0.9306],
         [1.0105],
         [0.8490],
         [0.9425],
         [1.0513],
         [1.1511],
         [0.8173],
         [0.8769],
         [1.1896],
         [0.8670],
         [0.8558],
         [0.8644],
         [0.8646],
         [0.8482],
         [0.8283],
         [1.1437],
         [1.0947],
         [0.8121],
         [0.9243],
         [1.2040],
         [1.0593],
         [1.1556],
         [1.0390],
         [0.9841],
         [1.0129],
         [0.9605],
         [1.0988],
         [0.8059],
         [0.9758],
         [1.1394],
         [0.9969],
         [1.1690],
         [0.8358],
       

In [17]:
for i in range(1000):
    optimizer.zero_grad()
    y_pred = model(x)["x"]
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()
    if i % 100 == 0:
        print(i, loss.item())

0 1.1633436679840088
100 0.06514652818441391
200 0.042637500911951065
300 0.02715247869491577
400 0.01718084141612053
500 0.011729205958545208
600 0.009142213501036167
700 0.008066040463745594
800 0.007671847939491272
900 0.007544530555605888


In [18]:
model.linear.mlp[0].weight, model.linear.mlp[0].bias

(Parameter containing:
 tensor([[1.9519]], requires_grad=True),
 Parameter containing:
 tensor([1.0141], requires_grad=True))