In [7]:
%load_ext autoreload
%autoreload 2

In [ ]:
import numpy as np

In [31]:
# test voxel downsample
from voxelization import VoxelDownsample

vd = VoxelDownsample(x_range=[-1, 1], y_range=[-1, 1], z_range=[-1, 1], 
                     voxel_size={"x":1,"y":1,"z":1})

pc = np.array([[-0.2,-0.3,0.],
               [-0.6,-0.4,0],
               [-0.3,0.7,0],
               [-0.1,0.8,0],
               [0.5,0.6,0],
               [0.6,0.9,0],
               [0.8,-0.3,0.],
               [0.1,-0.4,0]])

out = vd(pc)
print(out)


[[ 0.   -0.35 -0.4 ]
 [ 0.   -0.35  0.45]
 [ 0.    0.75 -0.2 ]
 [ 0.    0.75  0.55]]


In [18]:
import yaml

# read ./config/config.yaml

with open('./config/config.yaml', 'r') as file:
    config = yaml.safe_load(file)

print(config)

{'GNNLayers': [{'name': 'GNN_layer_1', 'mlp_h': {'dim_lst': [64, 64], 'activation': 'relu', 'output_activation': 'none'}, 'mlp_f': {'feat_dim': 32, 'hidden_dim_lst': [32, 32], 'activation': 'relu', 'output_activation': 'none'}, 'mlp_g': {'dim_lst': [64, 64], 'activation': 'relu', 'output_activation': 'none'}}, {'name': 'GNN_layer_2', 'mlp_h': {'dim_lst': [64, 64], 'activation': 'relu', 'output_activation': 'none'}, 'mlp_f': {'feat_dim': 32, 'hidden_dim_lst': [32, 32], 'activation': 'relu', 'output_activation': 'none'}, 'mlp_g': {'dim_lst': [64, 64], 'activation': 'relu', 'output_activation': 'none'}}], 'nuscenes': {'num_classes': 3, 'class_mappings': {'vehicle': ['car', 'truck', 'bendy bus', 'rigid bus', 'trailer', 'construction_vehicle', 'ambulance', 'police vehicle'], 'two_wheeler': ['motorcycle', 'bicycle'], 'human': ['adult pedestrian', 'child pedestrian', 'construction worker', 'police officier']}}}


In [20]:
config["nuscenes"]["class_mappings"]

{'vehicle': ['car',
  'truck',
  'bendy bus',
  'rigid bus',
  'trailer',
  'construction_vehicle',
  'ambulance',
  'police vehicle'],
 'two_wheeler': ['motorcycle', 'bicycle'],
 'human': ['adult pedestrian',
  'child pedestrian',
  'construction worker',
  'police officier']}

In [14]:
config["GNNLayers"]

[{'name': 'GNN_layer_1',
  'mlp_h': {'dim_lst': [64, 64],
   'activation': 'relu',
   'output_activation': 'none'},
  'mlp_f': {'feat_dim': 32,
   'hidden_dim_lst': [32, 32],
   'activation': 'relu',
   'output_activation': 'none'},
  'mlp_g': {'dim_lst': [64, 64],
   'activation': 'relu',
   'output_activation': 'none'}},
 {'name': 'GNN_layer_2',
  'mlp_h': {'dim_lst': [64, 64],
   'activation': 'relu',
   'output_activation': 'none'},
  'mlp_f': {'feat_dim': 32,
   'hidden_dim_lst': [32, 32],
   'activation': 'relu',
   'output_activation': 'none'},
  'mlp_g': {'dim_lst': [64, 64],
   'activation': 'relu',
   'output_activation': 'none'}}]

In [17]:
from gnn import GNN

gnn = GNN(config["GNNLayers"])
gnn

GNN(
  (layers): ModuleList(
    (0): GNNLayer(
      (mlph): MlpH(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      )
      (mlpg): MlpG(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      )
      (conv): PointGNNConv(
        mlp_h=MlpH(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      ),
        mlp_f=<gnn.MlpF object at 0x7fbb599f8a30>,
        mlp_g=MlpG(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      ),
      )
    )
    (1): GNNLayer(
      (mlph): MlpH(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      )
      (mlpg): MlpG(
        (mlp): Sequential(
          (0): Linear(in_features=64, out_features=64, bias=True)
        )
      )
      (conv): PointGNNConv(
        mlp_h=MlpH(
    

In [2]:
import itertools

list(itertools.product([-1,1], [-2,2],[-3,3]))

[(-1, -2, -3),
 (-1, -2, 3),
 (-1, 2, -3),
 (-1, 2, 3),
 (1, -2, -3),
 (1, -2, 3),
 (1, 2, -3),
 (1, 2, 3)]

In [3]:
import numpy as np
np.array([[1,2,3]]).T

array([[1],
       [2],
       [3]])

In [4]:
a = np.array([1,2,3,4,5])
b = (a>=1) & (a<=3)
b

array([ True,  True,  True, False, False])

In [5]:
np.array([[1,2,3,4]]).reshape(-1)

array([1, 2, 3, 4])